Repository googleapis/python-service-control, pull requests merged in 2021-04, with the labels that each got.

#6 chore: Update synth.py to work around generator issue
  google/cloud/servicecontrol_v1/types/distribution.py
  synth.py
Labels: api: servicecontrol, automerge, cla: yes

#8 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: servicecontrol, cla: yes, context: partial

#10 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: servicecontrol, cla: yes, context: full, samples

#12 chore: prevent normalization of semver versioning
  setup.py
Labels: api: servicecontrol, cla: yes

#13 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: servicecontrol, automerge, cla: yes, context: full

#16 chore(revert): revert preventing normalization
  setup.py
Labels: api: servicecontrol, cla: yes
